default_language_version:
  python: python3

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.3
    hooks:
      - id: ruff
        args: [--fix]
        files: ^backend/.*\.py$
      - id: ruff-format
        files: ^backend/.*\.py$

  - repo: local
    hooks:
      - id: pycodestyle
        name: pycodestyle
        entry: pycodestyle
        language: python
        additional_dependencies: [pycodestyle==2.12.1]
        args: [--max-line-length=88]
        files: ^backend/.*\.py$
        exclude: ^backend/.*/migrations/
